name: BookyWay scheduler - Python application

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create test report directory
      run: mkdir -p TestReportHtml

    - name: Run tests with pytest
      run: |
        pytest skip_burpees.py
      env:
        CI: true

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: TestReportHtml/report.html
