name: BookyWay scheduler - Python application

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Set up Xvfb and Chromedriver
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        sudo Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
        chromedriver --url-base=/wd/hub &
      env:
        DISPLAY: :99

    - name: Create test report directory
      run: mkdir -p TestReportHtml

    - name: Run tests with pytest
      run: |
        pytest skip_burpees.py --html=TestReportHtml/report.html
      env:
        CI: true

    - name: Upload test report
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: TestReportHtml/report.html
